"""initial_schema

Revision ID: b55f7a7dfb0c
Revises: 
Create Date: 2026-08-30 13:15:28.751314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55f7a7dfb0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_table('health_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_checks_target_type'), 'health_checks', ['target_type'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=32), nullable=False),
    sa.Column('last_health_check', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('credentials',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('provider_id', sa.String(length=12), nullable=False),
    sa.Column('key_masked', sa.String(length=64), nullable=True),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('usage_input', sa.Integer(), nullable=False),
    sa.Column('usage_output', sa.Integer(), nullable=False),
    sa.Column('usage_total', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.Text(), nullable=True),
    sa.Column('deactivated_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('provider_id', sa.String(length=12), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotation_events',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('provider_id', sa.String(length=12), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('old_credential_id', sa.String(length=12), nullable=True),
    sa.Column('new_credential_id', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('provider_id', sa.String(length=12), nullable=False),
    sa.Column('session_masked', sa.String(length=128), nullable=True),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_validated', sa.Text(), nullable=True),
    sa.Column('last_validation_error', sa.Text(), nullable=True),
    sa.Column('last_successful_fetch', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credential_id', sa.String(length=12), nullable=True),
    sa.Column('provider_id', sa.String(length=12), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('snapshot_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_snapshots')
    op.drop_table('sessions')
    op.drop_table('rotation_events')
    op.drop_table('models')
    op.drop_table('credentials')
    op.drop_table('settings')
    op.drop_table('providers')
    op.drop_index(op.f('ix_health_checks_target_type'), table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
