"""add next_validation_at to credentials

Revision ID: f2d8a87a8b44
Revises: d0c7aa2d0f36
Create Date: 2026-08-30 14:35:33.640583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d8a87a8b44'
down_revision: Union[str, Sequence[str], None] = 'd0c7aa2d0f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('next_validation_at', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'next_validation_at')
    # ### end Alembic commands ###
